add_newline = false

format = "$all"

[battery]
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
full_symbol = "ğŸ”‹"

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 60

[[battery.display]]
style = "bold green"
threshold = 100

[character]
# symbol = "âœ"
# error_symbol = "x"
# use_symbol_for_status = true

[cmd_duration]
format = "took [$duration]($style) "
min_time = 500

[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncate_to_repo = true
truncation_length = 6

[git_branch]
style = "bold purple"
truncation_length = 8
truncation_symbol = "..."

[git_state]
am = "AM"
am_or_rebase = "AM/REBASE"
bisect = "BISECTING"
cherry_pick = "CHERRY PICKING"
disabled = false
format = " of "
merge = "MERGING"
rebase = "REBASING"
revert = "REVERTING"
style = "bold yellow"

[git_status]
ahead = "ğŸğŸ’¨ ${count}"
behind = "ğŸ˜° ${count}"
conflicted = "ğŸ³ ${count}"
deleted = "ğŸ—‘ ${count}"
diverged = "ğŸğŸ’¨ ${ahead_count} ğŸ˜° ${behind_count}"
modified = "ğŸ“ ${count}"
renamed = "ğŸ“ ${count}"
staged = '[++\($count\)](bold green)'
stashed = "ğŸ“¦"
untracked = "ğŸ¤·"
up_to_date = "âœ…"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[hostname]
disabled = true
format = "[$hostname]($style) in "
ssh_only = false
trim_at = "."

[line_break]
disabled = false

[memory_usage]
disabled = false
style = "bold dimmed white"
symbol = "ğŸ’¾ "
threshold = -1

[nodejs]
disabled = false
style = "bold green"
symbol = "â¬¢ "

[python]
disabled = false
pyenv_prefix = "pyenv"
pyenv_version_name = false
style = "bold yellow"
symbol = "ğŸ "

# [time]
# format = "ğŸ•™%T"
# style_root = "bold red"
# style_user = "bold yellow"
# show_always = true
# disabled = false

[username]
style_user = "yellow bold"
# format = "[$user]($style) "
disabled = false
show_always = true
